=== SpocWeb/query-first/QueryFirst.SharedAll/JsonSchema/qfconfig.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "defaultConnection": {
      "type": "string"
    },
    "provider": {
      "enum": [
        "Microsoft.Data.SqlClient",
        "MySql.Data.MySqlClient",
        "Npgsql",
        "System.Data.SqlClient"
      ]
    },
    "generators": {
      "type": "array",
      "items": { "$ref": "#/$defs/generator" }
    },
    "connectEditor2DB": {
      "type": "boolean"
    },
    "helperAssemblies": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "$defs": {
    "generator": {
      "type": "object",
      "properties": {
        "name": {
          "enum": [
            "CSharp",
            "TsInterfaceFromDto"
          ]
        },
        "options": {
          "description": "Generators are loosely coupled. Options are passed as a string dictionary. Only strings here sorry.",
          "items": {
            "additionalProperties": {
              "type": "string"
            }
          },
          "type": "array"
        }
      }
    }
  }
}

=== SpocWeb/query-first/tests/TestTargets/SqlServerTestTarget/qfconfig.json
{
  "$schema": "../../../queryfirst.sharedall/jsonschema/qfconfig.schema.json#",
  "defaultConnection": "Data Source=s-dev4,1434;Database=QueryFirstTestDB;Trusted_Connection=True;Encrypt=false;",
  "provider": "Microsoft.Data.SqlClient",
  "connectEditor2DB": true,
  "helperAssemblies": [ "C:\\Users\\sboddy\\source\\repos\\query-first\\tests\\TestTargets\\TestHelperDll\\bin\\Debug\\net6.0\\TestHelperDll.dll" ]

}
